name: flutter_mvvm_example
description: Flutter MVVM example project.

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^0.1.2
  scoped_model: ^0.2.0
  font_awesome_flutter: ^7.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true 

  fonts:
    - family: Distant Galaxy
      fonts:
        - asset: fonts/DISTGRG_.ttf
